require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/reviews", type: :request do

  before do
    admin = Admin.create!(email: "test@test.ru", password: '1234567')
    sign_in admin
  end
  # This should return the minimal set of attributes required to create a valid
  # Review. As you add validations to Review, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
  {
    author_name: 'author',
    author_email: "author@u.ru",
    body: "short doby"
  }
  end
  let(:invalid_attributes) do
  {
    author_name: '',
      author_email: "",
      body: ""
  }
  end

  describe "GET /index" do
    it "renders a successful response" do
      Review.create! valid_attributes
      get "/admin/reviews"
      expect(response).to be_successful
    end
  end


end
